config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups do
    post :admin
    post :unadmin
  end
  root 'groups#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :admins
  has_one :owner, through: :admins, source: :user
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def display_name
      self.email.split("@").first
    end
    has_many :groups
    has_many :admins
    has_many :admin_groups, :through => :admins, :source => :group
    def is_admin_of?(group)
      admin_groups.include?(group)
    end

    def admin!(group)
      admin_groups << group
    end

    def unadmin!(group)
      admin_groups.delete(group)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_group, except: [:index, :new, :create]
  before_action :is_admin_of, only: [:edit, :update, :destroy]
  def index
    @groups = Group.all
  end

  def show
  end

  def edit
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      @group.user.admin!(@group)
      redirect_to "/"
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to "/"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to "/"
  end
  private

  def group_params
    params.require(:group).permit(:title, :description, :room, :password)
  end

  def find_group
    @group = Group.find(params[:id])
  end

  def is_admin_of
    @group = Group.find(params[:id])
    if !current_user.is_admin_of?(@group)
      flash[:alert] = "你不是主持人，无权操作！"
      redirect_to :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">线上meetup</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                <li><%= link_to("注册", new_user_registration_path) %> </li>
                <li><%= link_to("登录", new_user_session_path) %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.display_name %>
                      <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                      <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "标题", input_html: { class: "form-control"} %>
    <%= f.input :description, :label => "描述", input_html: { class: "form-control"} %>
    <%= f.input :room, :label => "房间号", input_html: { class: "form-control"} %>
    <%= f.input :password, :label => "密码", input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑meetup</h2>

    <hr>

    <%= render "form" %>

</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>id</td>
        <td>标题</td>
        <td>描述</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td> <%= group.id %></td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
              <% if current_user && current_user.is_admin_of?(group) %>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增meetup</h2>

    <hr>

    <%= render "form" %>

</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <span class="pull-right">
      <% if current_user && current_user.is_admin_of?(@group) %>
        <label class="label label-success"> 主持人 </label>
      <% end %>
    </span>
  <% if current_user && current_user.is_admin_of?(@group) %>
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
  <% end %>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>
  <p><%= @group.room %></p>
  <p><%= @group.password %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Olms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>        
        <%= yield %>
    </div>
        <%= render "common/footer" %>
  </body>
</html>